from django.urls import path

from core import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("inactive-account/", views.inactive_account_page, name="inactive_account_page"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_page, name="register"),
    path("admin/panel/", views.admin_panel, name="admin_panel"),
    path("admin/users/<int:user_id>/activate/", views.activate_user_account, name="activate_user_account"),
    path("api/accounts/check-username/", views.check_username, name="check_username"),
    path("api/accounts/check-referral/", views.check_referral, name="check_referral"),
    path("templates/", views.templates_gallery, name="templates_gallery"),
    path("cv/templates/", views.cv_templates, name="cv_templates"),
    path("cv/create/", views.cv_create_page, name="cv_create"),
    path("cv/build/<int:cv_id>/", views.cv_build_page, name="cv_build"),
    path("cv/download/<int:cv_id>/", views.download_cv, name="download_cv"),
    path("cv/download/latest/", views.download_latest_cv, name="download_latest_cv"),
    path("letters/", views.letters_home, name="letters_home"),
    path("letters/create/", views.letters_create_page, name="letters_create"),
    path("letters/edit/<int:letter_id>/", views.edit_letter, name="edit_letter"),
    path("letters/download/<int:letter_id>/", views.download_letter, name="download_letter"),
    path("api/cv/preview/", views.preview_cv, name="preview_cv"),
    path("api/cv/template-preview/<str:template_id>", views.template_preview, name="template_preview"),
    path("api/cv/template-preview/<str:template_id>/", views.template_preview),
    path("api/cv/render-template/", views.render_template_from_editor, name="render_template_from_editor"),
    path("api/ai/generate-cv/", views.generate_cv_from_ai, name="generate_cv_from_ai"),
    path("api/cv/save-draft/", views.save_cv_draft, name="save_cv_draft"),
    path("api/cv/<int:cv_id>/update/", views.update_cv_build, name="update_cv_build"),
    path("api/ai/extract-cv-basics/", views.extract_cv_basics, name="extract_cv_basics"),
    path("api/ai/extract-linkedin/", views.extract_linkedin_profile, name="extract_linkedin_profile"),
    path("api/voice/extract/", views.voice_extract_api, name="voice_extract_api"),
    path("api/voice/transcribe/", views.voice_transcribe_api, name="voice_transcribe_api"),
    path("api/letters/preview/", views.letter_preview_api, name="letter_preview_api"),
    path("api/letters/generate/", views.generate_letter_api, name="generate_letter_api"),
    path("api/letters/save/", views.save_letter_draft, name="save_letter_draft"),
    path("api/letters/enhance/", views.enhance_letter_api, name="enhance_letter_api"),
    path("api/cv/<int:cv_id>/generate-portfolio", views.generate_portfolio, name="generate_portfolio"),
    path("api/cv/<int:cv_id>/generate-portfolio/", views.generate_portfolio),
]
